// lib/sample-corpus.ts
// Four flavors of bundled corpora so the demo runs without an external dataset.

export interface SampleCorpus {
  id: string;
  name: string;
  description: string;
  text: string;
}

export const SAMPLE_CORPORA: SampleCorpus[] = [
  {
    id: "wiki",
    name: "Wikipedia-style",
    description: "Encyclopedic prose about natural language processing.",
    text: `Natural language processing is a subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language. It is in particular focused on how to program computers to process and analyze large amounts of natural language data. The goal is a computer capable of understanding the contents of documents, including the contextual nuances of the language within them. Once a computer has understood the contents, it can then accurately extract information and insights contained in the documents as well as categorize and organize the documents themselves. Challenges in natural language processing frequently involve speech recognition, natural language understanding, and natural language generation. Statistical methods, machine learning, and increasingly deep learning are used to attack these problems. Language models are central to nearly every natural language processing task. An n-gram language model assigns probabilities to sequences of words by counting how often each sequence appears in training data. A four gram model considers three previous words when predicting the next word. Smoothing techniques are used to assign nonzero probability to unseen events. Interpolation combines multiple lower order n-gram probabilities into a single estimate. Perplexity is the standard evaluation metric for language models and lower perplexity indicates a better model. Modern systems combine classical statistical models with neural network architectures such as recurrent networks and transformers. The transformer architecture introduced in twenty seventeen revolutionized the field by enabling massively parallel training on large corpora. Despite the dominance of neural methods, classical n-gram models remain useful for teaching, fast inference, and low resource scenarios. Researchers continue to study how to combine statistical and neural approaches for the best of both worlds.`,
  },
  {
    id: "news",
    name: "News-style",
    description: "Short news paragraphs with reporter-style sentences.",
    text: `Global markets opened higher on monday as investors weighed the latest inflation data from the united states. The federal reserve signaled it would remain cautious before adjusting interest rates again. Technology stocks led the rally, with several large companies posting record gains. Analysts said the broader index was responding to better than expected earnings reports. Meanwhile, oil prices slipped after producers agreed to maintain current output levels. In europe, manufacturing data showed a modest rebound, suggesting that the worst of the slowdown might be over. Asian markets also closed in positive territory, supported by strong export numbers from south korea and japan. Central banks across emerging markets are watching closely for signs that the dollar might weaken in the coming weeks. Economists at major banks have revised their growth forecasts upward. Trade negotiators from several countries are expected to meet later this month to discuss tariffs and supply chain resilience. Government officials emphasized that long term policy stability remains the top priority. Investors are also closely monitoring developments in the technology sector, where artificial intelligence companies continue to attract significant venture capital. New initial public offerings are being prepared, with bankers reporting strong investor interest. Markets are expected to remain volatile in the short term but the medium term outlook is increasingly optimistic. Analysts caution that geopolitical risks remain elevated and could quickly reverse recent gains.`,
  },
  {
    id: "lit",
    name: "Literature-style",
    description: "Classic prose passages with rich vocabulary and rhythm.",
    text: `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of light, it was the season of darkness, it was the spring of hope, it was the winter of despair. We had everything before us, we had nothing before us. The wind blew softly through the trees, carrying with it the scent of distant rain. In the small village by the river, lamps were being lit one by one, casting golden circles on the cobblestones. An old man sat by his door, watching the children play, his eyes bright with memory. He remembered his own youth, the long summers, the laughter of his sisters, the quiet evenings when his mother told stories of kings and brave travelers. The stars came out, slow and certain, and the village settled into a familiar peace. Somewhere far away, a bell rang out across the hills, and the old man smiled, for he knew the sound by heart. It was the bell of his childhood, of his town, of every winter and every spring he had ever known. Time, he thought, was a river that carried everything along with it, sometimes slowly and sometimes in great rushing torrents, but always forward, always away from where one had started. And yet, in the quiet hours, the river could be made to pause, and the past could be visited as one would visit an old friend.`,
  },
  {
    id: "ds",
    name: "AI / Data Science",
    description: "Technical writing about machine learning and statistics.",
    text: `Machine learning is a method of data analysis that automates analytical model building. It is a branch of artificial intelligence based on the idea that systems can learn from data, identify patterns, and make decisions with minimal human intervention. Supervised learning algorithms build a mathematical model of a set of data that contains both inputs and the desired outputs. The data is known as training data and consists of examples. Each training example has one or more inputs and the desired output, also known as a supervisory signal. In the mathematical model, each training example is represented as an array or vector, and the training data is represented as a matrix. Through iterative optimization of an objective function, supervised learning algorithms learn a function that can be used to predict the output associated with new inputs. Common supervised learning algorithms include linear regression, logistic regression, decision trees, random forests, gradient boosted trees, and neural networks. Unsupervised learning algorithms take a set of data that contains only inputs, and find structure in the data. The algorithms therefore learn from data that has not been classified or categorized. Clustering and dimensionality reduction are typical examples of unsupervised learning. Reinforcement learning is the study of how agents ought to take actions in an environment so as to maximize some notion of cumulative reward. Deep learning uses multilayer neural networks to learn representations of data with multiple levels of abstraction. Language models, image classifiers, and recommendation systems all benefit from these techniques. Evaluation metrics such as accuracy, precision, recall, and perplexity guide the iterative improvement of these systems.`,
  },
];
